var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                  o                          n  ",
   "                                x x x x x x x  yyyyyy              o     nnnnn  ",
   "                           o                               o     yyyyy       x  ",
   "                         xxxxx                           xxxxx               x  ",
   "                                x                                            x  ",
   "                                     o                                       x  ",
   "                                   yyyyy                                     x  ",
   "  +                                        o                                 x  ",
   "  x  @    o                               yyyy                               x  ",
   "  x     xxxxx                                       o                        x  ",
   "  xxxx                   o                       xxxxxx                      x  ",
   "  x                    yyyyy                                  o              x  ",
   "  x             o                                          yyyyyy            x  ",
   "  x           xxxxx              o                  o                        x  ",
   "  x                            xxxxx              xxxxx                      x  ",
   "  x                                        o                                 x  ",
   "  x                                      yyyyy                               x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  ",
   "  x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x  "],
  ["!x                                                                                                               x!",
   "!x                      o                                                                                        x!",
   "!x                    yyyyy                        nnnnn                                                         x!",
   "!x              o               o             o                                                                  x!",
   "!x            xxxxx           xxxxx         xxxxx                                                                x!",
   "!x      o                             o                                                                          x!",
   "!x    yyyyy                         yyyyy                                                                        x!",
   "!x          v                      v     v                                                                       x!",
   "!xx                                                                                                              x!",
   "!x  y                                                                                o        o        o         x!",
   "!x   x   o                                                                    o     xxxx    yyyy     xxxx        x!",
   "!x    yyyyyy                                                                yyyyy                          y     x!",
   "!x              o                                                     o                  v        v             xx!",
   "!x            xxxxxx                                                xxxxx         v                           yyyx!",
   "!x          v            o                                    o           v                                xx    x!",
   "!x                    yyyyyy                                yyyyy                                     o  y       x!",
   "!x                  v          o          o           o           v                                xxxxxx        x!",
   "!x                           xxxxxx     yyyyyy     xxxxxx                                   o                    x!",
   "!x                          v                                                            yyyyyyy                 x!",
   "!x                                  v v        v v        v                        o              v              x!",
   "!x                                                                              xxxxxx                           x!",
   "!x                                                                       o             v                         x!",
   "!x                                                                    yyyyyy                                     x!",
   "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    o              v                                  x!",
   "!x                                        x                 xxxxxxx                                              x!",
   "!x                                        x           @             v                                            x!",
   "!x                                        x         xxxx                                                         x!",
   "!x                                        x  +   xxxxxxxxxx                                                      x!",
   "!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["!x                                                                                                            ",
   "!x                                                                                                            ",
   "!x                                                                                                            ",
   "!x+                                                                                                           ",
   "!xxx  @                                                                                                       ",
   "xxxxxxxx           xxxxxx                                                                                     ",
   "       x           x                                                                                          ",
   "       x     p     x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "       x  x     x  x                                                                                          ",
   "       x    x      x                                                                                          ",
   "       x       p  px                                                                                          ",
   "       x p    x    x                                                                                          ",
   "       x      p p  x                                                                                          ",
   "       x  x        x                                                                                          ",
   "       x        x  x                                                                                          ",
   "       x   x   p   x                                                                                          ",
   "       x           x                                                                                          ",
   "       x p     x   x                                                                                          ",
   "       x   x   p   x                                                                                          ",
   "       x p   x     x                                                                                          ",
   "       x        p  x                                                                                          ",
   "       x x         xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "       x                                                                                                     x",
   "       xpppp                                           d                                                    dx",
   "       xxxxxxxxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxx              x",
   "                               x  o x           x o  x                 x  o x                 x  x    x      x",
   "                               xxxxxx           xxxxxx                 xxxxxx                 x    k     x   x",
   "                                                                                              x              x",
   "                                                                                              x   x   x      x",
   "                                                                                              x           k  x",
   "                                                                                              x k      k     x",
   "                                                                                              x    x         x",
   "                                                                                              x      x       x",
   "                                                                                              x  k        k  x",
   "                                                                                              x     x   x    x",
   "                                                                                              x  x    k      x",
   "              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx           k  x",
   "              x                                                                                    x         x",
   "              x                                                                                 k      x     x",
   "              x                                                                                              x",
   "              x                                                                                              x",
   "              x          o   o   o     o     o      o         o            o                                 x",
   "              xnnnnnnnn!xx!!xx!!xxx!!!xxx!!!xxxx!xxxxxx!!!!xxxxxxx!!!!xxxxxxxxxx!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],

   ["                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "  x     x   xxxxxxx  x     x                                                    ",
    "   x   x    x     x  x     x                                                    ",
    "     x      x     x  x     x                                                    ",
    "     x      x     x  x     x                                                    ",
    "     x      x     x  x     x                                                    ",
    "     x      xxxxxxx  xxxxxxx                                                    ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "  x             x  x  xx    x                                                   ",
    "   x     x     x      x x   x                                                   ",
    "    x   x x   x    x  x  x  x                                                   ",
    "     x x   x x     x  x   x x                                                   ",
    "      x     x      x  x    xx                                                   ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                ",
    "                                                                                "],

];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
